services:
  redis-test:
    image: redis:6.2-alpine
    ports:
      - 6379:6379

  redis-dev:
    image: redis:6.2-alpine
    ports:
      - 6378:6379

  web:
    image: ruby:3.3.0
    platform: linux/amd64 # force platform to avoid arm64 issue
    command: "/bin/bash"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "4567:4567"
    expose:
      - 4567
    volumes:
      - .:/workspace
    environment:
      RACK_ENV: "development"
      REDIS_DEV: "redis://redis-dev:6379"
      REDIS_TEST: "redis://redis-test:6379"
    depends_on:
      - redis-dev
      - redis-test



